name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.kt'
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  build-jar:
    name: Build Jar
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.9.0
      with:
          gradle-version: 8.4
    - name: Execute shadowJar
      run: ./gradlew shadowJar
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: jar-build
        path: build/libs/*-all.jar

  buildNative:
    name: Build Native Image
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs: build-jar
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Prepare directory
        run: |
          mkdir -p build/libs/out
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: jar-build
          path: build/libs/jar
      - name: Check
        run: |
          ls build/libs/jar
      - name: Build
        run: |
          native-image -jar build/libs/jar/*-all.jar build/libs/out/ktimage -H:+UnlockExperimentalVMOptions -H:EnableURLProtocols=http,https --no-fallback
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: native-image-${{ runner.os }}
          path: build/libs/out/
