# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  build-jar:
    name: Build Jar
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "Cache ~/.gradle/caches"
      uses: actions/cache@preview
      with:
        path: "~/.gradle/caches"
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
        restore-keys: ${{ runner.os }}-gradle-
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: shadowJar
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ktimage.jar
        path: build/libs/*-all.jar

  buildNative:
    runs-on: windows-latest
    needs: build-jar
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Prepare directory
        run: |
          mkdir -p build/libs/out
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: ktimage.jar
          path: build/libs/ktimage.jar
      - name: Check
        run: |
          ls build/libs/
      - name: Build
        run: |
          native-image -jar build/libs/ktimage.jar build/libs/out/ktimage -H:+UnlockExperimentalVMOptions -H:EnableURLProtocols=http,https --no-fallback
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Package
          path: build/libs/out/
